Implement dark mode
spq/pkappa2 pull request #80
Opened 2024-02-02 00:21 UTC by schmop

Its pretty:
![image](https://github.com/spq/pkappa2/assets/1284227/72f73ed5-216e-4b54-a81d-8f39329c6fff)
![image](https://github.com/spq/pkappa2/assets/1284227/59bcbd66-23bb-4fdf-970c-064433737cab)
![image](https://github.com/spq/pkappa2/assets/1284227/e9535716-e9aa-4ee7-ade1-e7174be0fe4d)
![image](https://github.com/spq/pkappa2/assets/1284227/316e54a3-a505-41e6-984a-45744397ffcf)

Streams in Lightmode are not as pretty atm:
![image](https://github.com/spq/pkappa2/assets/1284227/1d8dc6bf-3501-49f7-a7cb-31493df20fef)

2024-02-04 16:54 UTC, peace-maker approved these changes

2024-02-04 18:01 UTC, peace-maker requested changes
Tag colors in darkmode make text hard to read.
![grafik](https://github.com/spq/pkappa2/assets/1635147/35969ea2-e6a7-48bd-90a4-1c3c11aabe13)

When viewing the Graph component for the first time while no `colorScheme` entry is present in the local storage yet, it won't update when changing the scheme through the buttons in the menu. After refreshing the page it works though.

2024-05-02 21:42 UTC, spq commented
nice!

2024-05-26 20:37 UTC, peace-maker approved these changes

2024-05-26 20:38 UTC, merged